import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Tab Title</title>
        <meta
          name="description"
          content="Generated by next.js-typescript-tailwind.css 1sdc0d3r template"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main></main>

      <footer></footer>
    </div>
  );
};

export default Home;
