import type { NextPage } from 'next';
import Image from 'next/image';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div className="flex bg-blue-300">
      <Head>
        <title>Photo Portfolio</title>
        <meta
          name="description"
          content="Generated by next.js-typescript-tailwind.css 1sdc0d3r template"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Image
          src="/images/jellyfish/grey.jpeg"
          alt="Jellyfish with grey background"
          width={350}
          height={600}
          className=""
        />
        {/* <Image
          src="/images/jellyfish/blue.jpeg"
          alt="Jellyfish with blue background"
          width={300}
          height={300}
        /> */}
        <Image
          src="/images/dogs/darby-deer.JPG"
          alt=""
          width={300}
          height={300}
        />
        {/* <Image
          src="/images/rocks/glass_beach.jpeg"
          alt=""
          width={300}
          height={300}
        /> */}
        <Image src="/images/sun/cemetary.JPG" alt="" width={300} height={300} />
        <Image src="/images/sun/horses.jpeg" alt="" width={300} height={300} />
        <Image src="/images/sun/pier.JPG" alt="" width={200} height={600} />
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
