import type { NextPage } from 'next';
import Image from 'next/image';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div className="flex bg-blue-300">
      <Head>
        <title>Photo Portfolio</title>
        <meta
          name="description"
          content="Generated by next.js-typescript-tailwind.css 1sdc0d3r template"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full h-full">
        <Image
          src="/images/jellyfish/grey.jpeg"
          alt="Jellyfish with grey background"
          width={500}
          height={500}
          // className="m-0 p-0"
        />
        <Image
          src="/images/jellyfish/blue.jpeg"
          alt="Jellyfish with blue background"
          width={500}
          height={500}
        />
        <Image
          src="/images/dogs/darby-deer.JPG"
          alt=""
          width={500}
          height={500}
        />
        <Image
          src="/images/rocks/glass_beach.jpeg"
          alt=""
          width={500}
          height={500}
        />
        <Image src="/images/sun/cemetary.JPG" alt="" width={500} height={500} />
        <Image src="/images/sun/horses.jpeg" alt="" width={500} height={500} />
        <Image src="/images/sun/pier.JPG" alt="" width={500} height={500} />
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
